import { FolderData } from '../types/FolderData';

export const downloadFileCount = (folderData: FolderData) => {
	// Create the text content
	const content = `File Count Report
=================

Folder Path: ${folderData.path}
Scan Date: ${folderData.lastScanned.toLocaleString()}
Total Files: ${folderData.fileCount}

File List:
${folderData.files.map((file, index) => `${index + 1}. ${file}`).join('\n')}

---
Generated by Excel Generator
`;

	// Create a Blob with the content
	const blob = new Blob([content], { type: 'text/plain' });

	// Create a temporary URL for the blob
	const url = URL.createObjectURL(blob);

	// Create a temporary anchor element for download
	const link = document.createElement('a');
	link.href = url;
	link.download = `file-count-${folderData.path.replace(/[^a-zA-Z0-9]/g, '_')}-${new Date().toISOString().split('T')[0]}.txt`;
	
	// Trigger the download
	document.body.appendChild(link);
	link.click();
	
	// Cleanup
	document.body.removeChild(link);
	URL.revokeObjectURL(url);
};
